# Build and run a simple Rust application.

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: ./install-rust.sh
  displayName: 'Install rustup environment.'

- script: cargo build
  displayName: 'Build Rust application.'

- script: cargo run Azure-Build
  displayName: 'Run Rust application.'
