name: Rust_Build_Test

on: [push]

jobs:
  rust_build_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Install rustup environment.'
        run: ./install-rust.sh

      - name: 'Build Rust application.'
        run: cargo build

      - name: 'Run Rust application.'
        run: cargo run
